import React from 'react';
import { View, Text, StyleSheet } from 'react-native';

export const DetailItem: React.FC<{ label: string; value: string; theme: any }> = ({ label, value, theme }) => (
  <View style={[styles.detailBlock, { backgroundColor: theme.colors.elevation.level1 }]}>
    <Text style={[styles.detailBlockLabel, { color: theme.colors.onSurfaceVariant }]}>{label}</Text>
    <Text style={[styles.detailBlockValue, { color: theme.colors.onSurface }]}>{value}</Text>
  </View>
);

export const styles = StyleSheet.create({
  container: { flex: 1 },
  scroll: { padding: 16, paddingBottom: 40 },
  label: { fontSize: 15, fontWeight: '600', marginBottom: 6, marginTop: 14 },
  searchInput: { borderRadius: 10, padding: 14, borderWidth: 1, minHeight: 56 },
  nicknameInput: { borderRadius: 10, padding: 14, borderWidth: 1 },
  placeholder: { fontSize: 16 },
  selectedRow: { flexDirection: 'row', alignItems: 'center' },
  typeDot: { width: 10, height: 10, borderRadius: 5, marginRight: 10 },
  selectedInfo: { flex: 1 },
  selectedName: { fontSize: 16, fontWeight: '600' },
  selectedMeta: { fontSize: 12, marginTop: 2 },
  selectedBadges: { flexDirection: 'row', gap: 4 },
  miniBadge: { paddingHorizontal: 4, paddingVertical: 1, borderRadius: 3, fontSize: 9, fontWeight: '800' },
  modalOverlay: { flex: 1, backgroundColor: 'rgba(0,0,0,0.5)', justifyContent: 'flex-end' },
  modalContent: { borderTopLeftRadius: 20, borderTopRightRadius: 20, maxHeight: '90%', paddingBottom: 20 },
  modalHeader: { flexDirection: 'row', justifyContent: 'space-between', alignItems: 'center', padding: 16, borderBottomWidth: 1 },
  modalTitle: { fontSize: 18, fontWeight: '700' },
  closeBtn: { width: 32, height: 32, borderRadius: 16, justifyContent: 'center', alignItems: 'center' },
  closeBtnText: { fontSize: 16 },
  searchBarWrapper: { flexDirection: 'row', alignItems: 'center', margin: 12 },
  searchBar: { flex: 1, borderRadius: 10, padding: 12, fontSize: 16 },
  searchSpinner: { marginLeft: 8 },
  resultsCount: { fontSize: 12, paddingHorizontal: 16, marginBottom: 4 },
  legend: { flexDirection: 'row', paddingHorizontal: 16, paddingBottom: 8, gap: 12, flexWrap: 'wrap', alignItems: 'center' },
  legendSectionTitle: { fontSize: 12, fontWeight: '600' },
  legendItem: { flexDirection: 'row', alignItems: 'center', gap: 4 },
  legendDot: { width: 10, height: 10, borderRadius: 5 },
  legendText: { fontSize: 12 },
  loadMoreBtn: { padding: 14, alignItems: 'center', borderTopWidth: 1 },
  loadMoreText: { fontSize: 14, fontWeight: '600' },
  modalList: { maxHeight: 500 },
  emptyResults: { padding: 30, alignItems: 'center' },
  emptyResultsText: { fontSize: 16 },
  strainItem: { flexDirection: 'row', alignItems: 'center', padding: 14, borderBottomWidth: 1 },
  strainInfo: { flex: 1 },
  strainName: { fontSize: 16, fontWeight: '600' },
  strainMeta: { fontSize: 12, marginTop: 2 },
  badgeRow: { alignItems: 'flex-end', gap: 4 },
  typeBadge: { paddingHorizontal: 6, paddingVertical: 2, borderRadius: 4, fontSize: 10, fontWeight: '800' },
  difficultyBadge: { fontSize: 14 },
  detailCard: { borderRadius: 12, padding: 14, marginTop: 8, borderWidth: 1 },
  detailHeader: { flexDirection: 'row', alignItems: 'flex-start', marginBottom: 12 },
  detailBadges: { flexDirection: 'column', gap: 4, marginRight: 10 },
  detailTypeBadge: { paddingHorizontal: 8, paddingVertical: 3, borderRadius: 4 },
  detailTypeText: { fontSize: 10, fontWeight: '800', color: '#fff' },
  detailInfo: { flex: 1 },
  detailName: { fontSize: 20, fontWeight: '700' },
  detailBreeder: { fontSize: 13, marginTop: 2 },
  detailGrid: { flexDirection: 'row', flexWrap: 'wrap', gap: 8 },
  detailBlock: { borderRadius: 8, padding: 8, width: '47%' },
  detailBlockLabel: { fontSize: 10, fontWeight: '500' },
  detailBlockValue: { fontSize: 13, fontWeight: '600', marginTop: 2 },
  tagsRow: { flexDirection: 'row', flexWrap: 'wrap', alignItems: 'center', marginTop: 10, gap: 4 },
  tagsLabel: { fontSize: 12, marginRight: 6 },
  effectTag: { borderRadius: 12, paddingHorizontal: 8, paddingVertical: 3, marginRight: 4 },
  effectText: { fontSize: 11, fontWeight: '500' },
  flavorTag: { borderRadius: 12, paddingHorizontal: 8, paddingVertical: 3, marginRight: 4 },
  flavorText: { fontSize: 11, fontWeight: '500' },
  qtyRow: { flexDirection: 'row', alignItems: 'center', justifyContent: 'center', marginTop: 8 },
  qtyBtn: { width: 40, height: 40, borderRadius: 20, justifyContent: 'center', alignItems: 'center' },
  qtyBtnText: { fontSize: 24, fontWeight: 'bold' },
  qtyValue: { fontSize: 24, fontWeight: '700', marginHorizontal: 20, minWidth: 40, textAlign: 'center' },
  dateBtn: { borderRadius: 10, padding: 14, alignItems: 'center', borderWidth: 1 },
  dateBtnText: { fontSize: 16, fontWeight: '500' },
  previewCard: { borderRadius: 12, padding: 14, marginTop: 8, borderWidth: 1 },
  previewTitle: { fontSize: 15, fontWeight: '700', marginBottom: 8 },
  previewRow: { flexDirection: 'row', justifyContent: 'space-between', marginBottom: 4 },
  previewLabel: { fontSize: 14 },
  previewValue: { fontSize: 14, fontWeight: '600' },
  notesInput: { borderRadius: 10, padding: 12, fontSize: 16, borderWidth: 1 },
  textArea: { height: 80, textAlignVertical: 'top' },
  submitBtn: { borderRadius: 12, padding: 16, alignItems: 'center', marginTop: 20 },
  submitText: { fontSize: 17, fontWeight: '700' },
  stageRow: { flexDirection: 'row', flexWrap: 'wrap', gap: 6, marginTop: 4 },
  stageBtn: { flexDirection: 'row', alignItems: 'center', paddingHorizontal: 10, paddingVertical: 8, borderRadius: 8, borderWidth: 1, gap: 4 },
  stageIcon: { fontSize: 16 },
  stageBtnText: { fontSize: 12, fontWeight: '500' },
});
